# Generated by Django 5.1.2 on 2024-11-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0002_rename_chapitre_article_pvrecensement_designation_chapitre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventaire',
            old_name='Designation_materiels',
            new_name='Designation_des_matieres_et_objets',
        ),
        migrations.RenameField(
            model_name='pvrecensement',
            old_name='Designation_materiels',
            new_name='Designation_des_matieres_et_objets',
        ),
        migrations.RemoveField(
            model_name='etatapreciatif',
            name='Nom_et_qualite_du_depositaire_comptable',
        ),
        migrations.AddField(
            model_name='etatapreciatif',
            name='Du',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etatapreciatif',
            name='Gestion_de',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etatapreciatif',
            name='label_vie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etatapreciatif',
            name='labell_vie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etatapreciatif',
            name='labelll_vie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etatapreciatif',
            name='labellll_vie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etatapreciatif',
            name='labelllll_vie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='label_nom',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='labell_nom',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='pvrecensement',
            name='label_vie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pvrecensement',
            name='labell_vie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pvrecensement',
            name='labelll_vie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pvrecensement',
            name='labellll_vie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
